export interface IStaffs {
  id: number;
  uid: number;
  staff_code: string;
  comment: string;
  deleted: number;
  booking_online: number;
  is_agency: number;
  uid_agency_id:string | null;
  group_name: string[];
  avatar: string | null;
  user: IStaffs_USER;
  bed: [];
}

export interface IStaffs_USER {
  id: number;
  user_group_id: string[];
  email: string;
  facebook: string;
  fullname: string;
  telephone: string;
  birthday: string;
  sex: number;
  height: string | null;
  weight: string | null;
  address: string;
  nationality: number;
  province: number;
  district: number;
  ward: number;
  job: string;
  identify_number: string;
  image: string;
  identify_img: string;
  issue_date: string;
  issue_area: string;
  status: boolean;
  user_from_id: number;
  user_level_id: number;
  site_lang: string;
  site_currency: string;
  interest_service_id: string;
  deleted: boolean;
  created_date: string;
  modified_date: string;
  created_by_id: number;
  branch_id: number;
  customer_backup_code: string;
  due_date: string | null;
  loginable: boolean;
  stage_name: string;
  vocative: string;
  brand_app: number;
  staff_id_referral: string | number | null;
  platform: string | null;
  sip_user: string | null;
  has_omicall: boolean;
  gs_line_to: number;
  level_id: string | number | null;
  summary: string | null;
}